# Generated by Django 2.2.4 on 2019-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamamsazeh', '0002_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_name',
            field=models.CharField(default='image', max_length=300),
        ),
    ]
