# Generated by Django 2.2.4 on 2019-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamamsazeh', '0003_projectimage_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Album',
            field=models.ManyToManyField(blank=True, to='tamamsazeh.ProjectImage'),
        ),
    ]
