# Generated by Django 2.2.4 on 2019-09-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamamsazeh', '0007_auto_20190908_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
